# @baseUrl = https://demo_feed.tradingview.com
@baseUrl = http://127.0.0.1:3000
@Accept = application/json, text/plain, */*
@userAgent = Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Mobile Safari/537.36 _ITZ_IOS/_HHMALL_IOS_1.0

# config
# @name config
GET {{baseUrl}}/config HTTP/1.1
Content-Type: application/json
User-Agent: {{userAgent}}
Accept: {{Accept}}

###

# symbols
# @name symbols
GET {{baseUrl}}/symbols
    ?symbol=TAIFEX%3AFITXN
Content-Type: application/json
User-Agent: {{userAgent}}
Accept: {{Accept}}

###

# marks
# @name marks
GET {{baseUrl}}/marks
    ?symbol=FITXN
    &from=1521725400
    &to=2114352000
    &resolution=2D
Content-Type: application/json
User-Agent: {{userAgent}}
Accept: {{Accept}}

###

# timescale_marks
# @name timescale_marks
GET {{baseUrl}}/timescale_marks
    ?symbol=FITXN
    &from=1521725400
    &to=2114352000
    &resolution=2D
Content-Type: application/json
User-Agent: {{userAgent}}
Accept: {{Accept}}

###

# history
# @name history
GET {{baseUrl}}/history
    ?symbol=FITXN
    &from=1580743800
    &to=1588743900
    &resolution=1
Content-Type: application/json
User-Agent: {{userAgent}}
Accept: {{Accept}}

###
